[workspace]
authors = ["Garrett Bischof <bischofgarrett@gmail.com>"]
channels = ["conda-forge"]
name = "deep_designer"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]
ruff = "ruff check ."
mypy = "mypy ."
black = "black ."
pytest = "pytest"
deep_designer = "python deep_designer.py"
dd = "python deep_designer.py"
designer = "python designer.py"
validate = "python scripts/validate_design.py"

[dependencies]
python = ">=3.13.3,<3.14"
openai = ">=1.77.0,<2"
pycountry = ">=24.6.1,<25"
questionary = ">=2.1.0,<3"

[pypi-dependencies]
anthropic = ">=0.50.0, <0.51"
requests = "*"
click = "*"
sqlalchemy = "*"
pytest = "*"
black = ">=25.1.0, <26"
ruff = "*"
mypy = "*"
agno = ">=1.4.3, <2"
ango = { version = ">=1.1.6, <2", extras = ["openai"] }
googlesearch-python = ">=1.3.0, <2"
crawl4ai = ">=0.6.2, <0.7"
markdown-to-json = ">=2.1.2, <3"
